### ISSUE TITLE
Add progress bar (pb library)

### ISSUE THREAD

**Issue by jdorfman** [stickermule/rump#1] opened 2016-11-24 23:45 UTC
I believe that adding the [pb](https://github.com/cheggaaa/pb) library will help `rump`'s UX

**Comment by BDQ** [comment] 2016-11-30 16:54
@jdorfman I think that depends on knowing how much work we have to do or how long it might take, right I think we're just showing that it's doing something, not that we're x% complete.

**Comment by jdorfman** [comment] 2016-11-30 17:35
@BDQ feel free to mark `wontfix` and close it.

**Comment by adnanh** [comment] 2016-12-01 20:37
Maybe instead implement progress report on USR1 signal (if OS supports it) like the `dd` does?

**Comment by nixtrace** [comment] 2016-12-02 14:40
Yeah, I thought about showing the progress at first.

The problem is that one of the core ideas of Rump is scanning, so it can't know the total number of keys to be transferred when it starts transferring.

It scans over the keys in batches and transfers a batch.

That's the reason why the tool is currently outputting `>` and `.`.

A `>` means a batch of keys has been read from source, and a `.` means a batch of keys has been restored on destination.

Maybe we can think about a more expressive symbol/word to show for a batch of keys dumped/restored.

**Closed as completed** 2016-12-06 15:51 UTC
Labels: enhancement
